---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-sealed-secret
  namespace: feedback-services
spec:
  encryptedData:
    .dockerconfigjson: AgBRlBrCvYSoBcyp/8dbkFoO7Zn3NVWHo5scmzuM1DbJmX5HIWadkpt35OKzmQ0hXrR8eEhC4wvFifuDeNAznznBkzjl9iW38A4xR74s5KsPLey2NQP6gv1eOs2Bw1BpW1AqPiqjSpJZ5FMZMdIoR6dbnd2MOG7Qj1ABU7n/jF6a9kcNoR1rpn0d02VcwRnjy1IxmDaFnqvUCNJ6E+E3wB771l54Bi4Sy76WLWhHcCKJrF3a9BMRXbSg+vwysPXk592z3ToOL/PM31s10idniZkIojTluzWOr8xr5GP1qGirDedwjavpHJ1g7ZcDb49fEGMiG3ZMaziyOuuGl/oA31zuedZ+TCQW8Oz8WK9nDXrCoNXqVPaKmdTe6Ol/5muvzkXJ9tq5Uw9Kg8zZkmDghXfK3UgQJw68GjSrpzHl349ToSzxBnYpmufBUf7Htj9eylJY2ROSFKjtjHQogxVpBnp7lzN0bSgANmqj4o4YDO3VRIPm1IQ/56nCIxL67Pk0cnDOlRfxTgWDb2w/s0z1ZqjddjtYJ42ZQJNENmv/QUPGn01IULxQoMB1GhWzCz8kqmQH1s17JJseU3/z20oipqBkYGiwZOfMAX4dg/v9IADF0abfq4Z1FVTg1kHw09qAzdTsX20dERwLz5rpTits6aplCs6hOyiKVswcqNLS7TXjmZc+yiRouK/F+JdYBoUhLIKvwvg2tTNg6Tknzu6xAzYrq0IUWzAm85NzCQgGY2LzzMT77/XWADE8IRP9c+Cfw6Me3dR90Kwuvc0NbHoCxPFbghYlaRPEuLijLLY8i2yJZbLxnmVGsR0Vqb/L1Ofb0fAhCk9sskjE+dGt+zsvvf/jlmFoUyWU9YUgo9KMfglD/XWEyrb67OuO78XWpQDj
  template:
    metadata:
      name: docker-sealed-secret
      namespace: feedback-services
    type: kubernetes.io/dockerconfigjson
