---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-sealed-secret
  namespace: feedback-services
spec:
  encryptedData:
    combined_env: AgBBT6Oo0QfszjsG4DVt2ihvp2DT/xCCgYsBvTJ/7r86rLTX3kY2w59xe6RkjLe4iE+fATTeLQSTvUZFO4m4jRcAqBQyumBqtBH06m4LJLHYbAfhk2e+anszymlHIcFxUu7KcvDZbEV16G9UHLXpWDNVPIGaZuq8FEEMTXVVpltSKFCE8F4gBTb+7rk+rMSFIU+KopPjI/KQjz2luzORZDwiLT19sMtpNUEGg7/vpQX7cktvXG9kvamvsgK5oWWB/S/RnNNVItMLlxtPjrCbAmt7YLfp5OCUDXFWPX1Ajj3cDXkpEu5w/sFOVAsOoI+RN+nSLWxkyPRfvFFcZQcvZ/QaQD1799xmHpNgTxJfXydfLc6y6tXlSjIdZ1ZaESvce25miFMHntJhp2zujJupEXU6HXyxz6/tdegIZ+0PFkSmLKn5pqx+AoYBpkJo+805ifF4Nr1ES83Cb9THxVZ4frTmJvbLjMS71QJVTc2DZYjSMXRWZ4mzF4ztLlrDNNfgAOO/hN8eyMb0UzNUdDF6i8xTqtuBF9eznQ79ypg4+C2Imr6m/zBdsukv9H0BPfX4ewe2WVnem82s20tFaw12XQs8xacYAQG2QHlhTq3qeQhHfvz0t2pY7K3TKUXrsVSFn/gny70n9Xd3xyyQL4/nLVKLe3gBrmy6vkymMr5SXka57/qPEsROD6BexnnYTc8Gqa30g0/7gZEGUfmxTRkC8wLvP2zua7qV/v5fm2LvpiHTtMiC4t7m6zd3KbKLKD9jb6zQQG+B+5wBTOz8gC7SkJbV6FtfhzAyXxd2i16uZggYx7YxygYitbMbnJhEE7H5xoAnpSjmsvrUJmPBT4oNulpI89N6mM3cXBFhqTUWermErH56gjQw9elLWmf4to3gH7NbtTTk53DncwgkPu74rR8W9htcTXqMTlImGAwYU4oIKGBSsUOVoD0=
  template:
    metadata:
      name: frontend-sealed-secret
      namespace: feedback-services
