---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-user-sealed-secret
  namespace: kafka
spec:
  encryptedData:
    password: AgCIemlvhTowwq2EzC7zWcTX7yJYYAxqyagyjhF5qNIAreXq3XH6D18cpzbQTP0bFskhYZr/zNF5F7scX3uhO8ciCykHKXs4xd1PSDLBxdKNE8sAMdJvoWYrJad9iz8HeTkOSldtsSS8CIE/Ntk1MjZZxEPazIwrrjsr5rO8Buub62EAK0SBsh2v4AUkYU9IJy/N8LbwOcA+talXrbeaUxAQew5Lr8HY6VGDCXGVjb5g6yJIdaKNaZfQAJfw7yrv8QcaPZncR4GcPQ90ejqOtSKoy4IsBehd4dsDqhIJB6VwG6/2ZX6VMo5C+6Y17yRewbz1XYmVdreA8w2xPC0w6dOLqFpIFO8IUfnwZ5gKOsYOCSkQxf2ys2dCJCFeFs+zQmKKzKga18cXkUS6CMR7Fhbn5hx+m4TfOFe6Lj9pqkE91sAth1mQdcbnxPaU9bHxlHfSsZ0Ps1GkQxL25VlrhpY/lO2sASkfAkta+/N4mer2fIO7A1Vyj0Np4A8N+bYd4Qa4xPj9Mz9rlwBYUwmHK/4hUSt+s5f1xy9neWYRU6t1Cjo4cbFGh81FuTkyMGuRstSiB6z0/KfiddsdXkL5EFFLNO1SfS/Nyg929VKUUTSG6YfmTD9NLVPKKqT0oPpP4/QeqoJD6bWKtd12r26FbbxG2r/xS7tgVmN+JBAWhGqyP4EifAKTkF4q7sOrZI5dvj6sKeIK7HbDi4A=
    username: AgCVB8ruapWSlkSyiCAY2Ncti2cOavcgc/fDHRkvs87cWGYWD/3Oz15ItjGnWCoXoanhQ/WchJ6tyXJcoqCdHf9D87pRxy330UPhe0EezPJVziCqrwpmwqxqQ/qhtKhkjH2L9QhMCk3conTEKxdeJpuWmnSHyy+xIweuA9aiRp44y/rvXqMThJXJzBaQbFEbRUQlEEh15L/qYHQ0RLMov3OqJUTHVA7M5PLmc0iGvaR0ufEqUi94ijDm1oLX1Orq/CqOciSMgwkfb60NGjkstMDhuEo8Eet0wSg9Vr0DbNOQw6nqtSEiwWBiouTaYkTu2w2Dr4GusMk5CILZtRbd5huqre4z/2ppBbIjlTIpV5i9bVAu0hWvcyIUpV9FFl/VDi+xzjQ9kLlwD0LMC+SSn/PQF0a+3xalaF/dDlUU3n9fUJ8PjOEDD6gPvw7Y17/xJXwcrk9i4qgA1Dvb1Q26kJARjsr6I525XXq7uBS5C/tHfHZnE4udVaENAbLuJ3lRu7G1OGzzFAWyBenSQDAgsqAhE2eXEF3uBK4KjChjAHPrt2ARqz/9117HPupePs6kB6JAeeE2l4R+Zxwy+tcxCMHKW/NufKReWyc8j2B0CbStUq8yALJEJXGNbPJJgCi82O2QMQj3Q41StjSURJ3QvfHlg4JhltRiFW8tdPgiVAH/xov8rT2xq6heUeUb81uQhxJwVEJNX/u9q70=
  template:
    metadata:
      name: kafka-user-sealed-secret
      namespace: kafka
