---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-user-sealed-secret
  namespace: kafka
spec:
  encryptedData:
    password: AgADIycvIYi/vcWFOB0R39BCWG9foGKBoE0u00QK+pQAIxIeHX0hJQ+xHj6k9cq+lpC1JUP0vStFg+df1IDx6k5sLhvnXTi+TiQ1NHuOyPUUg+720PUAwd2shtCXXDuHkSn7W03LnXEBuHDEytcU48X3oy7PbfwgnHDN1XJsG9IE6kAosphu/DBhirc1DLGQNTQmdNXFOl6IkqNHSnM5AJpqaAYWybRXBiF5vJ8qrr2abbYdNCtY2ZgT6Fis52AdARnMkAHFaBLB4+cnivOkMS0rHCdD1EYOyaFLkSya73cfQQy1TKlhvy/Hy24uddyck2uuZ4RPK1HTG4pJpbEtQ9sf1lauYVIJju9+HCYxQ37NltlsxsmlhGNu9TjqZyMbs/MP/F6k5RiMT/czTuZX9Jy5NKq+DOsev5HsHzEu/t3wf1WU8aZm4uoNffOf2Wj3BrWdszlXah/IftDzK3ZYp2wdNIwQeBjxzEXYm2SH3SF9KlRUYnzu+yWN21fLXGmKmAI5J+h6oVDsPIKppORg3cmMAzsbDEOg3O9b5ZgAOkO2jQTZETvVy6HXpjkS193/C/Wv6r8SDJl7yUgbeVtRuiu1Qt8FZ2ojeMvqXhoBPOTUeM4eSxbdK30z1NAcW+vfyViVudo+sjEuGsIFFfVSjsoS9prLAVWR+07np/Poii3po2KYb9n6Ap//AMmtVTsXvBz4gA23wihOmPw=
    username: AgCF7+8X45/rNJ+xEhNr/I/uZO6KP+gzwYCbDELu5WRSD3OdhqT/CuMTcOA2UsglPoCNhGIyLP6AvnPvd2xe3Eu/LZ+O1xIkN4Spz6RjhQZAXsii4Jh+WaYgzfCYIUtNDX3USEFds9IS6hxUJ+uO0rIjmdxTSjqg1AidFDKjvtAwzPOCmeGDWORCtmtMX89F/3yhULCFiVBxYTPly4oc7K7NWOYhDzQ0H/4IuRKXh6woQCrNdAGztjH1ZldVFftKnRsPU8+ENAyhw5wR9BIIcYIN4IYtSCcxrwDisbCX3MCILZtzLFEkWt3fnqJdbxywgYEZok+s74bC5izDzTdsEeH3v/RH0TV+XHj4GVCzXiTKvJK5JpMT08ouTVAKBMBxzmAqXzPhNCrhXWFBS9o8ihlz+3SJ33HEUKZTU/KAEMyS5CBVshav+/1iiGPfpygl9MxOVTBVd6Si/NHsPJaW6+agNHnMopza1JMSC/tL70av8GKovZ0HFP8iMZHsmIm2+44EcoY8ivv7dJoYTDTv10vFxn/Uchx9C6WJng9MyLNjgj3q0T3P8ITh24au2Zd8QN5aNeLayDSTtVB/okZV10V9aiq2h418YVmS/hA1LfzYmLygOGPXYNBWtEsWdDgRxRaf2I9g1WvE7g0SEyGHfSTu3vPem8mt/yzKWZcYzadEuQKm5dccUQQhKhWz7gENnYGcGCdGjTaFGGs=
  template:
    metadata:
      name: kafka-user-sealed-secret
      namespace: kafka
