---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-user-sealed-secret
  namespace: kafka
spec:
  encryptedData:
    password: AgAm2if3v5Fp6a6oe2Uss7Gr6RJEmZGRZl9HD0ZKjgYiXgleA0QBeCDRez/QUmeZiWDhCw2iSsd9PoWSWgbHhJU3vs7MsE+qO/XX53pCAkEfh+NAuEuRPmZyiTTRiXCbVxJn8bAr4Rrg0b5FZs8e91xtDg0x0bNEy2wqvZk/SirIaA/xbiXs9HRTYM3azJI7q3qOfa7DGYL6ZaTpeJgPv/ClWo3o6dbfrxAUmH6CekwVHy4ffpiHxB9/dbepknhpGBHiDPXb7GEND4QReSFWW+/dOjnfQfEBR/ubnuEN981rg1Tg538C4baE4m70lkZV0lhukAXNMq5fO5HgQbHaVqjfGEMtPFmgzb1VJDuRwdP6/oaYyCvkxpw/ssk+nHNR01gbIa/TUkIph4w0EVvAkaT06Zs6lAE2mYTIDuaJiYk5/XaScK4OzcgyLryY/GPKvqg4yhgnAPjFQelvac0Lxdx9KMALwVyG6fjmIcwaHxFYDW102zFJbmVnByjn4PcjOQVNy3zpZ+Xxyz9yKkQA9fivIkRw68nyI7V8lu+EJXrT6bUKXlZAYjtepCIX3/3BUILD1P7YcvC5K/x4S59d7RlPLovH6nUL4lQyekkESMxElgSGoj2aJOJLY9wVuOZAaKWBboNvojQVgVfsfLVqDxEFGYn8XA/7E+vk9rju/0khiE5Cfg29pYPtSJoctChqzVZzZKcUrNe2Lw8=
    username: AgCpNItZ+gG+o0PwWipf2nJzyPgdIJNwvYhH6g4GSy7JH/d3VB3ZD7ukfA7NFWlVNEcD5GP3/5993sXkjTqHwJiV69OKS4z/tp1JCEYXVyUC7axVTQz4KSQsuLMjxpqwP/wTTRWPxzAPnPAvtTJCWcqfeg/aKLQy5FM7GTIAoaB0GDvU0M1AOIxbxLsjEg74BTF7CYj9t3B42Nor39qkvlZRfe0PXWF3/OhVaB4O/EKHgipD0JODGwV8ROzVuNEv0V9yYckeEmbFZTh0htWYLDPr2NrE77ZE8h86t6LC1zkLlwDoMsik4qSYCh3cbkEGg7/6OnWlL9IsY3FLiaojOU1qLH/LNpB9YoI/MLfBkRkNCJTBSZwtodyhHyaBNb9ChVZBIHkoXVfPEFNchJ3uHCeOAlpOhHQyjL8EeV6GSipFSWyqisepJTBFsbxyOcdWsUwSWM1fsSQ7sJ8LCbOshiVJCAhK2rTuFcpUq6D+qQGsNivI0q4muzuHAczYas90ojzmfOR8Bc6gYiFTWBYyOBQKOROysdKtmO35iiNOq8PosIEQN1cJQn8oI1hdd/4qJnxNGpQdwdbiB4EOSFr0XtoiE540Epa3aDraP9v8joF4VxrhGDLy6qX33EWNlI9cpG6D+RH7oztPdLRSWdNdossn3gcfBbHxSP/jahQ/+806fb2JAv/WZEox6zW8GLuyAFWc7SZpSHCi2FI=
  template:
    metadata:
      name: kafka-user-sealed-secret
      namespace: kafka
