---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-user-sealed-secret
  namespace: kafka
spec:
  encryptedData:
    password: AgBq9nRKXeRC0elt+P2dgYCJzVmWKBaqYDVT6j/mi8l0gMfXUVWUtG8FoYj8mxN4dAoBcWnGNGmflgu9uWcvuac2I+I7QC1lzpw5VUU28uGgIYKNDkzwynzDemPzLdBPGbqQCSGNNMhrzXHNi8oVpkIHZoowzYWsQ76lxXBjIQ6lp2dAUYsFEWh89i+13IHk1H0wDkFJhkY4PHUX+EKQ/DClGEHSJVgBGY7XSVrNG7DfZJBwJ+zR74TXbnP2MX9p6Hd7lAHBXV3M6CdWaH4Vpwjps7rNNgCUf8Zjk4K6KO9UP76k9aJeW1Rt2GsdYLe5zB2KURAaZmJ/FD/cF5DCsBccMX1HzhcYN1lD8qVQ79ZZeVbWgVBKiGQhf54t37nOznMw8WBcCkdvEtzZAeHhEWoQqaUT5Es/rSTPijKeEqumOvu4hbaUqM8K+k/8giaGD2VNxQHfDOvIlVzliMnvDFwMP3q5/wD0AAsM8WO5KA8BR3y8N1ZSVddaDJvdrHqb0mMnN4l6+MldO1ImbkinlZW/o7cCUNTF3KWwuCTOZukfLBYHW8g8u+CIXgEd0Y0UcbHzUqDtLeb9X1g/A2uYxjllQPSzs60cn510TtH2B8+iyZUqwKAZPl8xkJWQY6wljknM/s1kazqRY9+vm0rGAxssNVOijpltPz2t4ljYD8y0AJnWtJsYRFA6ir9RcR6B8u0aKueUECq1EqA=
    username: AgACkZYEpVNKxe9hsiTGn8OYyUda2kBReTO1Rtky3vXbLMA2u3BP5A0oyyQ8eYFgWsd11uFnd99Rmwi2MIF3me7J0rJ8Uogr27wEapFUixhNVEe/u8FOvq6tsSvwm4yatMCMXL9V4aySyRFXK5W/PQq296hwlg1sRQTUTWzRyKqEmz8/g5g0k5WQxoob+YgkKhOPXtbvR2P643hgsd2adCQdQ+1LAYgBswZlkNvhAgvlktSWpPn3GgIt+s/ljI4eSOrLgb/enfZIheTz5Jg1mcfJP9ROClis/4zPSJRFOTMMY7L7+26AEiUUCw7EoSWK5QfcmTlJiFylBh7sRhB2i+lSHSP/TgBx9kQWt7fYWZhPe56vT3qEanjtT8fFzxmo8Z9dPgUWoB/7oG7a89LkX1PdN+i6NQqaqehvUOl+K3rzSs41nDS+h4+agm8FagvwSEV4/zJ23cnw7VLxPmk6zJkefAaPbJEfqgryP8tBXJHJlCRGJwnWEGluEfqLkxMwkV35nR4VBeRLAnYFR+rBAJwlgS8M19TPvqWO5xb6om5AcsnwRvDflO7Y8PIWXetq7rnMsJZH1VH1B+DHOqNGjyhByZedkRZnDwS6HWaGolBiJ1eWaGmh3yTpEDjJ0oJf+SUoA25hnNtk+vtmq5J6rOxdAv+yXQn/U9F/oLX33sL4zACCxbxJTTST2/kG0CEljpkSyiXJDx0rpVM=
  template:
    metadata:
      name: kafka-user-sealed-secret
      namespace: kafka
