---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-user-sealed-secret
  namespace: kafka
spec:
  encryptedData:
    password: AgCNlc5saV8Jx/ccSqgiY0bh7reLNGGKRV6zgtzFbaKNYRcLvZvLbK7WR/j2WqRx6aEtGeIRkplH5HnIbvEfczQb/7xDg8K7LaP/zfL0q4ASpAIyuKP7kHdJwKQhyaPRsn7aJ0NjGSlTQ/M+r/IZKmW2ZFcrHIuryE4Qir5GoDfWi0zSBzsReLA1wJcfUtnvcvMKIfogh0tYj7PNQahkR8y0XWuPDihunjmP5WeMv16H+oijbjNJ9RuMco4bB/AXy+8xBqYpE1cah9IeiWwjnY2IxK5j5bHeBWYEGI8XEbhL8hPNqHqbRwN1jHPCQdUx6MJVvy0L3fUMUJe9ClZLgNOyVf9JKhNoSW3cNGi54WCkT8GoYxKHKhSVVDBwJHddEaEWtUFXZrayTb8hQfMxpdpyj1iLcXv+oiCBkcVln5rRuw5WoySNHqsFe2sANL2kM5ACbeSLiWK8OVf0CYyku2c8gM8s84RyS0n9n5KJAjOzgWrQ6BmtqM7pN44RtH1CtFcnLmsNwY5ZzqSMPKyQLES7Hc42/EJiZ80GhucX+M9qyzmYltcDiJW5XOodD1GurB9AWFWfv47PtnQ4CkLZz+aQqG1+XMVP1SlQeXRPgIF8ff7tJcAOgaZy7vTxeD9FVQYDbPDVUS8E15vurKH15FujWpdj6od1C1PwUmZ97sp1iZGrfFmXAJFnFa20GObMw8RpWQWXT5RYgQ0=
    username: AgB6VKx8AN7M4NOptv9yCymI/XQxOgzeHWf70rNQAno/iitzjXs1z1aXk0aoFGTSSughDWOylu3Xp8dy7Z2vyjjx9O1xc0hOAuN18zeJHzpRi2vkYzwqlRxs4PUlSy7yqLX/MviJzmWk0mh7MLvUqmk7D9oaINSdQOAd2HS3LjJ5oGoDEloJg5U+8K/pUfemgPBkUPfDze3m3MNsQlk0ezJZSvEStcZRnMAgP62mf+RAFlBkiv5sHisC2tkCSCNkdfGohS07l8PVSIBo2GpP7cGNQrYxIPeDO8TbsaIZPUg1mYMhzPVsiqEx4shgkV4QF34/XNqtfeQwbyH+S5UEtDC08EoeKpmpKJQHq4jj7QiFB/zps1skBy8i3TxpNEMSw7+c8oiDT6FTSwYUu9nBPCh5MTiqrYfwcSEMPg9Mkf2/YXbUk/1kf5V1O65azfAQ1nK89L0MWvZlM6phYk5yz42F5oStfh1DSZdmDEMdsExrdFCCoYdYlzUFccYmQntTsYfES5rqQZQE30tQzi2t3X3SL7Xbgm1HGRR+y7OF6gWOYYY0dZXV/2eM9avmTP2ixUoNfSXtIYANS/gJpqLTor2m5M0xudM7+qpguMmLkA5eraLrNCvSjvn32qjVB8OzQKmGBPMk60jHKaBelCbqcxBHjatamtdfpketL8BURGU84UbM8Kr5njy0sxbmQTu9uzHt4PfFwXp/UEY=
  template:
    metadata:
      name: kafka-user-sealed-secret
      namespace: kafka
