---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-user-sealed-secret
  namespace: kafka
spec:
  encryptedData:
    password: AgClGWRYLHfv+6yCUuS6NA6eBVqx3kc06Jo6x25KdaMsiwOks86vgQj4myrDFlzo3rtzvt/cfgi5tjjzqfR0pE91nCfOzOEgrBXv0hpESexZnQCtummDUc0q4JEM/rakPiCBxoiMY6lqCvbVTlQ5bdQbmKdbVF1pIlN+yV80OS8WFw5lPq/HHI+Ko8DKeIE0IuUQbbPij74dMtuPwi1i73bfMSDTUzJqasr/iLOJz9rGJBmRYtmaTshyUzlfmmJgC2szVTibD6WcKrZvXztPrHlm15sy+RTHYD4sQJ825K2RBIpRPihD9wyg6weabZRyeT9XYJuWiMSII41RQbVi42Dxxw0uy3O6ATbAsqMhJZfpVCYovaMoZHykUdf/S8Fe7fiadAbaSPU/O4ePcbgFoe84GRcaf0IuzBkZaFNLTRMOz3wA/SUn40D3Jyp2JUfTgmN8PxXLz0N+YkkzkCgF08/OgnGvP2CnmoRHRXtFgiHaRhN16fZ8pXtLcTL/cFIaxKOL/uJdKsNWf+9g4rL2cvZ871epekYvQxvqk3/DSaXUcpXceDah+4x+4Vhq70SEkZaEfkCfW3oQGnY8N80rKF3MK8HUX8v+5dQXLwX0IQuB70u3W2QafdEXNiftXoTcUB/5Gaf03cPK7v5NznLaDivs2ee8E3HZ1gnUSU9Gs2J+QOov7wNMwau5e+v9k2Ke6kF01UJ11ZLMNSw=
    username: AgCnOTsC8j7vRQYc2aai5IdPrWDPAbmNRuzWNpk0pLYP87+0boxcBLlA8AVlkTVASRgTClXIY+/NpQuMMR88uGx59qlSE0H97rH4vDiuHdqtXvIOjtxRJEgyfaSatyxgTVRgzO2JqLBx/HXawVo9XNP2HIQVHWW60cg3Sa5y9cyWO3meULU75/VntLwMa2VjT3kMAPr9/k9W4afMI+Qz6q74ZQDYAYAvXqD/GtaxJArA2acyKTh4iXPaPpleUWrxtOYW3voSx6tNtL5/8WWuIiG7QUKxhIsVLoPicVxQl3iI7yuxaPVGDan9hIl60Hwsk9uO9dwQ13Gx+HL273CuDmqXGB4Z1POWdwAa9XXkIFofjv54zz3oE4paNHgV1mtiE9N4mHSo8v+J6yB+lwn6e3sEvQL5/mGnLCcn/DhSMxKnYklcPd4YnbJ8snbtWdMbJdMjNtqxQPdx8cO+6MTZbGLUTpmdsZmIZ8YHgDdXBa6/20J10/bnRYytZSyI1EvSDq3bWX4SLcOnaJhAHLLAyU10jL59nb7wzViIpYEIDOez1qusWKic5Go57CXy6QAy1KT6WikGbcDUEta4qw/1bkHkeo0KGYguTVsDZcWs/xSBeHAR/AaLaYA8w/+R8P9zkD6pLVZLq/4r3AcEdaFTd1/ddiIy1HzqSNna4dSEJEdnbCxz5jSV1saCaZvBTjziQKLtFO6Z3RMdxA0=
  template:
    metadata:
      name: kafka-user-sealed-secret
      namespace: kafka
