---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-user-sealed-secret
  namespace: kafka
spec:
  encryptedData:
    password: AgBYvslmTm9h5ztyQoxoJmfDqFDQ84V9jNpm+9GF6fd3VGJfCdVBjo+SupCWTYZMdIf4/o5J+3hKG4PZQaLljzdnHQPcXXK9Vza5KG+//PRb7RLq3+4vQ7dz3+xIQHZqc7DWW9QXlIPmyntweriXuRcuFyBqmSAZzAQD5T/P4Tz1tau7jmAkyjubSjlfVKxsXdd7Gs0OwpNNaHFLCzNzvGVALo4kOsmR9YQVfUGBdP9M+Q/HRpdHXoOLtXsVpCt+6t4cyqALE9DCwrVEHOXOVJBurNw5VWYleRgGmOLmH0ANBFGuJd6/pg5m12CtumCazPDNSAtNtNS3Ma+K0gqatPPLLa6u5OFg8ht0ngEcePsk0F5PJBEhJEBTJuWHXUP5Q0/MaaMZzr/HliNK7DEgNH9WgBtK9wZMg3SoPMLRZ24M8svZrUQArl9f+ued3wtgJNEKMm2Jezji0UoaF3tE2mcP8iBvjHkkY62gtK08RhBQv1gMDMsiM0dN74/d4rNVmJ+dTtupOSYH4OCDZorbnyETfMQDEoDdE5F2w4DiSBKtIT7Xr9FLe8xE9nr1PZH5avdCpXaY+f5Hq+MRr/cCnqq8S4Wjx1wUt8gkkQrISF90BLuYKC9PT9qU/Gq72iFAPanITA5BHYekXbSaa8hLtjk5sOB+CQm/XcEe/7ioCFGww3aC8ezgznnUjmz0NwVl+v7zipcPi7Mo564=
    username: AgBQ73//J0I6xb9lRLeErSFykWmcSLxGxjItLY7jqEfo2m3rjPKsM+KApDbUoCIl0biMSpJhMergLZdoRbhPqcrMLv4iLn8Zx1VKCyDzPlVaht6sVH5At3qX5rjv7P6swE1iNfSdLBa+lleJSX+zRCYtBtpKbwnkjLqtvjGcbUePnj7Ruk/9A4hOewrgJ0IxBtzH7PYvjEvSrhPUqjIhS8RkQGBYVT4Om729/CC+Ye//GysBKfPBdjCS5o/bpDZzkFTomsVpS7l0Fa3AgJn1oCU6dz2FnxKSeJFXPdZOqEk66jmfjP97POKV5qAWX7t6DNYgwpIKu5NCJ3VC+wbP2FBp29K+/uM1NHCadkedE0QYW4Uo5Xha+KjkTawnH9QYhpDovvJ2Kuci2FdngCLN2zPPdxVEbr94JfDIpsuLPwYq7fYwfdij12qfyh6mB3U9SDltHWWj5NpHy1L0UPHqaP8CLwj0AW8lNoFQjAGoBaLj3lQEVxcqB19iOBaOIHe054qrXKnhAvPEwaHKgPDMi9nzQvxmSF7ydshCsPImfOwDsFj+8QCvsdkoFkFAXEOMwZdrNnMhqtfUVZ5dSyCUlfz6FWBP6ObAAv2AzdAVHA+5ZPg3jue5txSPp8ao20sGEqoO5drxe08MU/ihanNPHr9N9DtMkSrr1gcOuQNmMJOVd/XLvjAacppbi1r/uzrmczKi/up4FCBRtbU=
  template:
    metadata:
      name: kafka-user-sealed-secret
      namespace: kafka
