---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ws-sealed-secret
  namespace: feedback-services
spec:
  encryptedData:
    combined_env: AgB/GdpnUU8LZtLANkxKzNuhwDHAzKjzXRvKIF8Ez154PJhimDG8A9+veDoi4iM2S/mIveAoWOiY7piXEE3fOHfr7YaysT+Ebqwp6pBF8Ats97lqGLWHHSzGMir6nKTIacZSXa4w1kUICatsbw2PYOhVFqwCCkwJe5ZUKPse3L4nOcPJUMqpJqTD37kAUBde1OG5QrEjoF+2FJbGg6KXQy/KBQZICRra/DwzI7/7a9hNY/l8NVbQV6jaFU++C+Q0pSoGE+W8MV9FCvxlQsfG7iIp4yq4Ig+9zdAMSwzfSy55xI8qDxUUSYEMzKtlmuA9/rajmb/JCCS4I0ZCS4+0/PqNSXGs/tRHI3plqw97y2m/99qONP+jDhwGIMT8efePIoOFw/YAhb3UGqepQCfQo6BDkZXyArn1mele1VchYsKyKBybpDSdlSPOPombdVG2iocAbwvu02aE9l+95ttCwnA6FPv+fIDDZqgF1mt+5M3+O564hclYrRZYRWuT1y6F67pWSH8WtywvhgpkQ8L5Nx4cT59bp7oufBvgIzBKPO73tCzI0MIcvPdPPwGOjXphjOJSOt7BVZvjsKusq1LKudshUdfi65ioQOyrksNxrCxKnUTKHNmb36nKRxraNYQ9k9/NYXILoVnLoMqTZgk7p1EQqECusST9MA1wd0hSkdPtLeXKu/n3CD/fXCxywOgBg2aYO1iIAJSuq5Hh4+2zyPwm0X3nL8ViN9memxhu9kwJEYR+2PiGTAsteEiJP9jcK7vNiMiB6IwJ6DZfty7BF2qKM9XWuSbBuFQrlWcSZJDy8J2IfR1/1Y2fcOOJH4IVDfN6YXmLWcx+a3ascfGe1uabaqCp3MMnqm+7pKC8YrIdiHnDiLYhFlgory7LNxgMYC0F
  template:
    metadata:
      name: ws-sealed-secret
      namespace: feedback-services
