---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ws-sealed-secret
  namespace: feedback-services
spec:
  encryptedData:
    combined_env: AgCbuPARi2bx5h1GJqMLnq06jzcgHHRSFjm5diosxHFG5agGjYyF4+FxPkh2wRxzdsvsOHNdPbJ11zB9G/gAUe1guQvXe2gSuluj2dSrMkwCw20cf5CiBVKo/VDrOul9OJIuA9PLrnNMusXLtM6b2c9Blrvn3fdQ/DHxlxVFTgq5AVjVW9AANzsY4lqmntv4Z6ue/+HEwBR+sbjICgcfeDMCrko39PveQgYcmiWvXLfFOs0xSzdKT9c+Dhl65Nul9NkyKF4Cv7Wnk4iENSkjWZ/jQ7+uY0nuLIOj/B84afh0X/B0MjqFbfp0HKBia5fzj9XieyN0CHrptNXFER6JcP6f8ZYy+1M/n5yM5h6+PcgVoZvJ+60CUeKATxgJfrGQh/n3R6I08ch+xNmEfL4rj9Iezqv3KQd8eIevLHi8r9GPXs0UmLrbu0owZwGfW7U/VSRPznMRLfn55GSnrqpEbdQTnnIwusP1ypOTvKfchn1AWPbhE222jnK8TnVb7C4AXFt5Rez1olUVUfKo/IVYwtcDwKr+P+VKDpmGpmYf6cWmHLGcQONRcwrj8ddDByERA4jOkJ1NhS3MjVuccDoKA1csDRI1/2BtnZLOi3IOKySL28WfF9a/B4ppq92D3ErZM/PFBw+0U67SGc5gyACWXLO+1R/oHWUC8981kfmILXvAeVvoUqS/IEr/bGIhzbjnfe0RggPmJ1e8WbzGIa9VwYxWfkN1OgRZLCLIOLbY8n0H12RaU6W8yWYNpT0BCF7zqlPoj8u5zqGaKO8Q29rtLSsQygDKBeqBFKHGpJwD+WNt0lqSXgSnOUgJXGqURAwsFmY3xcrFl4OELJ+0PIUdWftmzvMhYRLPvpJ4CEKstm77HuJcDrqpzBjS9Y0Wv4zFaA5e
  template:
    metadata:
      name: ws-sealed-secret
      namespace: feedback-services
