services:
  - name: kafka_consumer1
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-consumer1:578e5ba23020ffe6b88b1423cc626d56349340f1
    port: 80
    targetPort: 3005
    nodePort: 30083
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
