services:
  - name: kafka_consumer1
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-consumer1:a5a08b463574043447f4a77a12f0c33c9a137818
    port: 80
    targetPort: 3005
    nodePort: 30083
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
