services:
  - name: kafka_consumer1
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-consumer1:b9a884f2f960a32a45cc76879855e0fdb6e0f892
    port: 80
    targetPort: 3005
    nodePort: 30083
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
