services:
  - name: kafka_consumer1
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-consumer1:14459c6d40b2f3c39626ee0f1ee6291cff763cf1
    port: 80
    targetPort: 3005
    nodePort: 30083
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
