apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: kafka
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
    strimzi.io/cluster: feedback-cluster
spec:
  replicas: 2
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi
        class: fast-ssd
        kraftMetadata: shared
        deleteClaim: false