{{- range $key, $svc := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $svc.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ $svc.name }}
  ports:
    - protocol: TCP
      port: {{ $svc.port }}
      targetPort: {{ $svc.targetPort }}
---
{{- end }}
