apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-daemonset-reader
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["vpcresources.k8s.aws"]
  resources: ["cninodes"]
  verbs: ["get", "list", "watch"]
