services:
  - name: ws-server
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-ws-server:578e5ba23020ffe6b88b1423cc626d56349340f1
    port: 80
    targetPort: 8080
    nodePort: 30082
    secretRef: ws-sealed-secret
    dockersecretRef: docker-sealed-secret
