services:
  - name: ws-server
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-ws-server:a5a08b463574043447f4a77a12f0c33c9a137818
    port: 80
    targetPort: 8080
    nodePort: 30082
    secretRef: ws-sealed-secret
    dockersecretRef: docker-sealed-secret
