services:
  - name: ws-server
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-ws-server:a2067d0c4711d56f8a9d0f3107972c5b79bc5f2f
    port: 80
    targetPort: 8080
    nodePort: 30082
    secretRef: ws-sealed-secret
    dockersecretRef: docker-sealed-secret
