services:
  - name: ws-server
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-ws-server:f2177008b8433d2cbaab9a15ecde2e74aa73a788
    port: 80
    targetPort: 8080
    nodePort: 30082
    secretRef: ws-sealed-secret
    dockersecretRef: docker-sealed-secret
