services:
  - name: ws-server
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-ws-server:b9a884f2f960a32a45cc76879855e0fdb6e0f892
    port: 80
    targetPort: 8080
    nodePort: 30082
    secretRef: ws-sealed-secret
    dockersecretRef: docker-sealed-secret
