---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-sealed-secret
  namespace: feedback-services
spec:
  encryptedData:
    .dockerconfigjson: AgCiGVIxRJmuUq2NMUh15oxr1IrNcySgecncg/7zkEhyNXWHlpUAPDoms9EKIWIuDM5TAD4iyNux0jUTCDFP7Jw7SQU1MI3riCuVcEle6pNDOU4i2ETaawFvntdmUKNx2VoIZJ4OPrAh6ea9jEGHBw+Q6oZG46agSZWBOV812rgQXbxhPQd2zC+I/Hm0E5aijp10bEBe8avEJS7GsdQ2wbtZO4PQXhPgx1qI9cdG+g4KXDftIa/NJjtXonxGlYoJC6umSqiQvjW3DKa6/dxXlfF6C8DETHE4pLBJM/23+NN2Y+SEoisLPS67NuppnlA32v3eW+eXnlr5Tqs8jc/TYQt0KpcSQlPWXnBwEKln4G8MGUXXg71+ATHbxef5dKISh/o9uGmLrx5jbDAcLsa1HcRWYVqAA6X97g8MtErReerelREwM5t7+SYWusnv0Lv9/TZzFx+kbcmJvOJOy/Csi8Zj85T5b7OASUkoXH39BN5ftTY/orC7VuilEE8zF7WfPlCg7DBafkmBCgDzipz/6ms9WrVWlBfDml93TZBMXFC7NcNx7cWkSYeaUoP1fb4rC0POKIrBCdQ4cKB2PAb2FHtTDlhBnpzn/8ausQelb5NPBY0t2rjooC3NY/cwBjvg5L5QVXAnBV2YjNzEDFtsn5xPdKHGtJTaJBiP94m88EkP0t92/u0eQAE68n9wlBRKmQoduolJR1dPsrD26djOAtZmMaRhogtWYxUsPK2Nz/bWGLbNZHGzvkCArJPPSAhTYywMkAbBjD4WEUP3dsYRYp0JWFK3Q/+HPNBY2TV1b5n2/A9i3Ptc74iC+rblK98ENTO5qyNHmOFz4znIDwGrwqRfvNZpPs1Gcx3fYucFc6ECQbzF50hhvZ+6VEk9F6Fa
  template:
    metadata:
      name: docker-sealed-secret
      namespace: feedback-services
    type: kubernetes.io/dockerconfigjson
