services:  
  - name: kafka_consumer2
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/kafka_consumer2:23a8a90cb9af2ea2af5fb20a2cd8bfe7bd280033
    port: 80
    targetPort: 3004
    nodePort: 30084
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
