services:
  - name: kafka_consumer2
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-consumer2:578e5ba23020ffe6b88b1423cc626d56349340f1
    port: 80
    targetPort: 3004
    nodePort: 30084
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
