services:
  - name: kafka_consumer2
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-consumer2:f2177008b8433d2cbaab9a15ecde2e74aa73a788
    port: 80
    targetPort: 3004
    nodePort: 30084
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
