services:
  - name: kafka_consumer2
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-consumer2:a2067d0c4711d56f8a9d0f3107972c5b79bc5f2f
    port: 80
    targetPort: 3004
    nodePort: 30084
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
