services:
  - name: kafka_consumer2
    namespace: feedback-services
    replicas: 1
    image: bhatvinay7/reach-consumer2:2ef07359d2d3ebfce5010eb9ffc3f1fd7dc2e1ea
    port: 80
    targetPort: 3004
    nodePort: 30084
    secretRef: kafka_consumer-sealed-secret
    dockersecretRef: docker-sealed-secret
