apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: feedback-services
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory

    email: bhatvinay75@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
